import fnmatch
import re
from pathlib import Path

IGNORE_FILENAME = ".leakscanignore"
LEGACY_IGNORE_FILENAME = ".secretignore"

DEFAULT_IGNORES = [
    "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico", "*.svg",
    "*.pdf", "*.zip", "*.tar", "*.gz", "*.bin", "*.exe",
    "*.lock", "*.sum",
    ".git/**", "node_modules/**", "__pycache__/**", ".venv/**",
    "*.pyc", "*.pyo",
]

INIT_TEMPLATE = """\
# .leakscanignore
#
# Patterns use .gitignore-style syntax:
#   - blank lines and lines starting with # are ignored
#   - a trailing / marks a directory and everything under it
#   - a leading ! re-includes a path that an earlier pattern ignored
#
# Generated by `leakscan init`.

tests/
docs/
*.md
fixtures/
fake_*.py
*_test.py
*_mock.py
"""


def _glob_to_regex(pattern: str) -> re.Pattern:
    pattern = pattern.replace("\\", "/")

    if pattern.startswith("**/"):
        pattern = pattern[3:]
        prefix = "(?:.*/)?"
    else:
        prefix = ""

    if pattern.endswith("/**"):
        pattern = pattern[:-3]
        suffix = "(?:/.*)?"
    elif pattern == "**":
        pattern = ""
        suffix = ".*"
    else:
        suffix = ""

    parts = pattern.split("/") if pattern else []
    regex_parts = []
    for part in parts:
        if part == "**":
            regex_parts.append(".*")
        else:
            regex_parts.append(re.escape(part).replace(r"\*", "[^/]*").replace(r"\?", "[^/]"))

    body = "/".join(regex_parts)
    return re.compile("^" + prefix + body + suffix + "$")


def _matches(rel_str: str, pattern: str) -> bool:
    normalized = rel_str.replace("\\", "/")
    name = normalized.split("/")[-1]

    if pattern.endswith("/"):
        base = pattern.rstrip("/")
        if "/" not in base and "**" not in base:
            # Bare directory name (e.g. "tests/") matches at any depth.
            pattern = f"**/{base}/**"
        else:
            pattern = f"{base}/**"

    if "**" not in pattern and "/" not in pattern:
        return fnmatch.fnmatch(name, pattern)

    if "**" in pattern:
        try:
            return bool(_glob_to_regex(pattern).match(normalized))
        except re.error:
            return False

    return fnmatch.fnmatch(normalized, pattern)


def _read_pattern_lines(path: Path) -> list[str]:
    patterns = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    return patterns


def load_ignore_patterns(root: Path) -> list[str]:
    """Build the ordered list of ignore patterns for a scan.

    Patterns are applied in order with .gitignore-style negation, so
    later patterns (including those in .leakscanignore) can override
    earlier ones (including the built-in defaults).
    """
    patterns = list(DEFAULT_IGNORES)

    for filename in (LEGACY_IGNORE_FILENAME, IGNORE_FILENAME):
        ignore_file = root / filename
        if ignore_file.is_file():
            patterns.extend(_read_pattern_lines(ignore_file))

    return patterns


def is_ignored(path: Path, root: Path, patterns: list[str]) -> bool:
    """Return True if path should be ignored.

    Patterns are evaluated in order; a pattern prefixed with "!"
    re-includes a path that a previous pattern ignored. The last
    matching pattern wins, mirroring .gitignore semantics.
    """
    try:
        relative = path.relative_to(root)
    except ValueError:
        relative = path

    rel_str = str(relative)

    ignored = False
    for pattern in patterns:
        if pattern.startswith("!"):
            if _matches(rel_str, pattern[1:]):
                ignored = False
        else:
            if _matches(rel_str, pattern):
                ignored = True

    return ignored


def get_ignore_file_path(root: Path) -> Path:
    return root / IGNORE_FILENAME


def append_ignore_pattern(root: Path, pattern: str) -> Path:
    """Append a pattern to .leakscanignore, creating the file if needed.

    Returns the path to the ignore file.
    """
    ignore_file = get_ignore_file_path(root)
    is_new = not ignore_file.exists()

    with open(ignore_file, "a", encoding="utf-8") as f:
        if is_new:
            f.write("# .leakscanignore - patterns for leakscan to skip (gitignore syntax)\n")
        f.write(pattern.strip() + "\n")

    return ignore_file


def write_init_template(root: Path) -> tuple[Path, bool]:
    """Create .leakscanignore with the default template if it doesn't exist.

    Returns (path, created) where created is False if the file already existed.
    """
    ignore_file = get_ignore_file_path(root)
    if ignore_file.exists():
        return ignore_file, False

    ignore_file.write_text(INIT_TEMPLATE, encoding="utf-8")
    return ignore_file, True
